// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN2eMLuPO-MT-3JUTiKbY0WhYRXfUxjSU',
    appId: '1:218769205666:web:aa95b7a7cbe3b9345b6afb',
    messagingSenderId: '218769205666',
    projectId: 'flutter-tutorial-756e8',
    authDomain: 'flutter-tutorial-756e8.firebaseapp.com',
    storageBucket: 'flutter-tutorial-756e8.appspot.com',
    measurementId: 'G-X6SSQ19ZZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeMwtYcGcvK0DCSUEPNzbrXyHE7K8VGq4',
    appId: '1:218769205666:android:05060110df35ab945b6afb',
    messagingSenderId: '218769205666',
    projectId: 'flutter-tutorial-756e8',
    storageBucket: 'flutter-tutorial-756e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaZf_AkgEfynBQk5wTKnHLwXdidNUHlhM',
    appId: '1:218769205666:ios:72a98982694f80f25b6afb',
    messagingSenderId: '218769205666',
    projectId: 'flutter-tutorial-756e8',
    storageBucket: 'flutter-tutorial-756e8.appspot.com',
    iosClientId: '218769205666-4vd3p7iskmtbmij56sek8vm0s8tt03eb.apps.googleusercontent.com',
    iosBundleId: 'xxx.domain.flutterapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaZf_AkgEfynBQk5wTKnHLwXdidNUHlhM',
    appId: '1:218769205666:ios:38ff082f71d33b915b6afb',
    messagingSenderId: '218769205666',
    projectId: 'flutter-tutorial-756e8',
    storageBucket: 'flutter-tutorial-756e8.appspot.com',
    iosClientId: '218769205666-rok2gtr2dbkhf81itms2ibk8krrep6ha.apps.googleusercontent.com',
    iosBundleId: 'xxx.domain.flutterapp.RunnerTests',
  );
}
